/**
 * Expo config plugin that re-applies the build-host thread constraints to
 * android/gradle.properties on every `expo prebuild`.
 *
 * WHY (PAP-1661): the b135 release build died with
 *
 *     unable to create native thread: possibly out of memory or process/
 *     resource limits reached
 *
 * which is not a memory problem. Every agent on this host shares one
 * `paperclip.service` cgroup with `pids.max=600`; `pids.current` sits around
 * 300-430 while other agents are awake and `pids.events` already recorded
 * `max 8`, i.e. the cap had been hit eight times. An unconstrained Gradle
 * build — parallel workers plus a forked daemon JVM plus a Kotlin daemon
 * plus Metro's node workers, every one of them sizing its internal pools off
 * 8 CPUs — reliably exhausts whatever headroom is left.
 *
 * The constraints below fixed b135. They previously lived only in
 * android/gradle.properties, which is gitignored AND regenerated by
 * `expo prebuild`, so they evaporated on the next prebuild and the next agent
 * got to rediscover an intermittent failure whose message points at memory and
 * whose reproducibility depends on how many other agents happen to be awake.
 *
 * This plugin is the prebuild-side half of the fix. The other half lives in
 * scripts/lib/gradle-constraints.sh, which passes the same settings on the
 * `./gradlew` command line — that covers a stale or hand-edited android/ tree
 * that no prebuild has touched. Belt and braces, because the failure mode is
 * intermittent and expensive to diagnose.
 *
 * If this repo ever builds somewhere that is NOT thread-capped, these are pure
 * pessimisation (a 1-worker, daemon-less build is markedly slower) and both
 * halves should be gated on the host rather than deleted piecemeal.
 */
const { withGradleProperties } = require('expo/config-plugins');

/**
 * Single source of truth for the constraint set. scripts/lib/gradle-constraints.sh
 * carries the same values; keep the two in sync.
 */
const JVM_ARGS = '-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ActiveProcessorCount=2';

const PROPERTIES = [
  // Caps the daemon JVM's own thread pools (GC, JIT, ForkJoinPool.commonPool),
  // all of which are sized off Runtime.availableProcessors() = 8 otherwise.
  ['org.gradle.jvmargs', JVM_ARGS],
  // One project at a time.
  ['org.gradle.parallel', 'false'],
  // One worker process at a time.
  ['org.gradle.workers.max', '1'],
  // No long-lived daemon left holding threads after the build.
  ['org.gradle.daemon', 'false'],
  // The file-system watcher spawns inotify threads per watched hierarchy.
  ['org.gradle.vfs.watch', 'false'],
  // Compile Kotlin inside the Gradle process instead of forking a Kotlin daemon JVM.
  ['kotlin.compiler.execution.strategy', 'in-process'],
  // Incremental compilation keeps extra daemon-side state and workers; the
  // android/ tree is regenerated anyway so there is little to reuse.
  ['kotlin.incremental', 'false'],
];

const MARKER = 'PAP-1661 build-host thread constraints';

const HEADER =
  ' ' + MARKER + ' — applied by ' +
  'mobile/plugins/withBuildHostGradleProps.js. Do not hand-edit: android/ is ' +
  'gitignored and regenerated by `expo prebuild`. Edit the plugin instead.';

module.exports = function withBuildHostGradleProps(config) {
  return withGradleProperties(config, (cfg) => {
    const keys = new Set(PROPERTIES.map(([k]) => k));
    // Drop any prebuild-generated or previously-injected entry for these keys —
    // and our own header — so re-running the plugin over an already-patched file
    // is idempotent and ours is the value that wins.
    cfg.modResults = cfg.modResults.filter(
      (item) =>
        !(item.type === 'property' && keys.has(item.key)) &&
        !(item.type === 'comment' && String(item.value).includes(MARKER))
    );
    const last = cfg.modResults[cfg.modResults.length - 1];
    if (last && last.type !== 'empty') cfg.modResults.push({ type: 'empty' });
    cfg.modResults.push({ type: 'comment', value: HEADER });
    for (const [key, value] of PROPERTIES) {
      cfg.modResults.push({ type: 'property', key, value });
    }
    return cfg;
  });
};
