/**
 * PAP-1694 (option A) — Expo config plugin for the native preprocess kernels.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so every piece
 * of native wiring has to be reapplied from here.  This plugin:
 *
 *   1. copies mobile/cpp/*.{h,cpp} into android/app/src/main/cpp/
 *   2. writes android/app/src/main/cpp/CMakeLists.txt (our library) *and*
 *      android/app/src/main/jni/CMakeLists.txt (the app's `appmodules`
 *      target) — see the note on APP_CMAKE below, this split is load-bearing
 *   3. adds `buildFeatures { prefab true }` + `externalNativeBuild` to
 *      android/app/build.gradle
 *   4. writes GearKernelsModule.kt / GearKernelsPackage.kt
 *   5. registers GearKernelsPackage in MainApplication.kt
 *
 * Why our own kernels rather than react-native-fast-opencv's: that binding
 * exposes no CLAHE at all and its cv::Canny is a different algorithm from ours
 * (IoU 0.437 against the JS edge map).  Routing preprocess through it would
 * change the edge map that the whole detect stage consumes, i.e. an accuracy
 * change requiring a corpus re-baseline — which is what AC5 forbids.  The C++
 * here is a line-by-line port of src/algorithm/imageUtils.js and is verified
 * byte-identical over the corpus by __tests__/pap1694.native-parity.mjs.
 * fast-opencv stays linked for the detect port (PAP-1696), which needs
 * cv::dft.
 */
const {
  withDangerousMod,
  withAppBuildGradle,
  withMainApplication,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const CPP_SOURCES = [
  'gear_kernels.h',
  'gear_kernels.cpp',
  'GearKernelsJsi.h',
  'GearKernelsJsi.cpp',
  'GearKernelsJni.cpp',
];

// -ffp-contract=off is load-bearing, not hygiene: with contraction enabled
// clang is free to fuse the `a*b + c*d` terms of the CLAHE bilinear blend into
// FMAs, which keeps more intermediate precision than the JS does and shifts
// Math.round by one at ties.  That alone would break byte parity.
// `externalNativeBuild.cmake.path` is winner-takes-all: React Native's Gradle
// plugin only installs its own default app setup when the app has not set one
// (NdkConfiguratorUtils.kt:34, `if (ext.externalNativeBuild.cmake.path ==
// null)`).  With newArchEnabled=true, that default setup is what builds
// `libappmodules.so` — the library MainApplication's `loadReactNative()` loads
// and the one that registers every autolinked C++ TurboModule, including
// react-native-fast-opencv's.  Pointing the app at a CMakeLists that only
// builds our kernels therefore does not "add" a library, it *replaces* the
// app's, and the build produces no libappmodules.so at all.
//
// So the app-level CMakeLists is the framework's documented customisation
// recipe (see ReactAndroid/cmake-utils/default-app-setup/CMakeLists.txt):
// project(appmodules) + include ReactNative-application.cmake, with our
// library pulled in beside it.
//
// It lives in src/main/jni/ and holds no .cpp of its own on purpose:
// ReactNative-application.cmake globs `*.cpp` next to the including
// CMakeLists and, if it finds any, compiles *those* as appmodules instead of
// the framework's OnLoad.cpp.  Our sources sit in src/main/cpp/ so that glob
// stays empty and OnLoad.cpp — hence autolinking registration — survives.
const APP_CMAKE = `# Generated by mobile/plugins/withGearKernelsPlugin.js — do not edit in place.
cmake_minimum_required(VERSION 3.13)

project(appmodules)

include(\${REACT_ANDROID_DIR}/cmake-utils/ReactNative-application.cmake)

# PAP-1694: our exact-semantics preprocess kernels, built alongside appmodules
# so AGP packages libgearkernels.so into the same APK.
add_subdirectory(\${CMAKE_CURRENT_SOURCE_DIR}/../cpp gearkernels_build)
`;

// -ffp-contract=off is load-bearing, not hygiene: with contraction enabled
// clang is free to fuse the `a*b + c*d` terms of the CLAHE bilinear blend into
// FMAs, which keeps more intermediate precision than the JS does and shifts
// Math.round by one at ties.  That alone would break byte parity.
//
// No project() call here — this file is always pulled in by APP_CMAKE, and a
// nested project() would take CMAKE_PROJECT_NAME away from `appmodules`, which
// ReactNative-application.cmake uses to name the target it builds.
//
// Everything below is set as a *target* property, never as a CMAKE_* directory
// variable: this file is `add_subdirectory`d, so a directory variable set here
// would not reach `appmodules` (correct) but would also silently do nothing if
// the file were ever included instead.  Target properties fail loudly instead.
//
// The C++ standard has to be stated explicitly.  RN applies `-std=c++20` per
// target via `target_compile_reactnative_options()`
// (ReactCommon/cmake-utils/react-native-flags.cmake:17), and it is called only
// for `appmodules` — nothing sets CMAKE_CXX_STANDARD anywhere in the app
// build, so an unset standard here means "whatever this NDK's clang happens to
// default to", which is not something parity should rest on.  We pin c++20 to
// match the framework, and pap1694.native-parity.mjs is run at both c++17 and
// c++20 to show the choice is parity-neutral.  -fexceptions/-frtti are
// likewise explicit because jsi.h throws jsi::JSError and uses dynamic_cast.
const KERNELS_CMAKE = `# Generated by mobile/plugins/withGearKernelsPlugin.js — do not edit in place.
# Included from ../jni/CMakeLists.txt; not a standalone CMake project.

find_package(ReactAndroid REQUIRED CONFIG)

add_library(gearkernels SHARED
  gear_kernels.cpp
  GearKernelsJsi.cpp
  GearKernelsJni.cpp
)

# Must match the flags mobile/__tests__/pap1694.native-parity.mjs proves parity
# under.  See the note in the plugin source — -ffp-contract=off in particular
# is load-bearing, not hygiene.
target_compile_options(gearkernels PRIVATE
  -ffp-contract=off
  -fno-fast-math
  -fexceptions
  -frtti
)
set_target_properties(gearkernels PROPERTIES
  CXX_STANDARD 20
  CXX_STANDARD_REQUIRED ON
  CXX_EXTENSIONS OFF
)

# ReactNative-application.cmake turns on IPO for the whole app build when the
# toolchain supports it.  Parity was proven without it, so keep this target on
# the same footing as the harness that verified it.
set_target_properties(gearkernels PROPERTIES INTERPROCEDURAL_OPTIMIZATION FALSE)

target_include_directories(gearkernels PRIVATE \${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(gearkernels
  ReactAndroid::jsi
  android
  log
)
`;

const MODULE_KT = (pkg) => `package ${pkg}

import android.util.Log
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * PAP-1694 — installs the native preprocess kernels onto the JS runtime.
 *
 * Generated by mobile/plugins/withGearKernelsPlugin.js.
 *
 * \`install()\` is a blocking synchronous method because it has to run on the JS
 * thread with the runtime alive: it hands the jsi::Runtime pointer to C++,
 * which sets \`globalThis.__gearKernels\`.  JS calls it once, lazily, from
 * src/algorithm/nativeKernels.js and falls back to the pure-JS backend if it
 * returns false — a device without the .so must still count teeth.
 */
class GearKernelsModule(reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = NAME

  private external fun nativeInstall(jsiRuntimeRef: Long)

  @ReactMethod(isBlockingSynchronousMethod = true)
  fun install(): Boolean {
    if (!loadLibraryOnce()) return false
    return try {
      val ref = reactApplicationContext.javaScriptContextHolder?.get() ?: 0L
      if (ref == 0L) {
        Log.w(NAME, "no jsi runtime pointer available; staying on the JS backend")
        return false
      }
      nativeInstall(ref)
      true
    } catch (e: Throwable) {
      Log.e(NAME, "install failed; staying on the JS backend", e)
      false
    }
  }

  companion object {
    private const val NAME = "GearKernels"

    // Loaded lazily rather than in a static initialiser: an UnsatisfiedLinkError
    // in \`init\` would surface as ExceptionInInitializerError at module
    // construction and take the whole native-module registry down with it.
    @Volatile private var libraryState: Boolean? = null

    @Synchronized
    private fun loadLibraryOnce(): Boolean {
      libraryState?.let { return it }
      val ok = try {
        System.loadLibrary("gearkernels")
        true
      } catch (e: Throwable) {
        Log.e(NAME, "libgearkernels.so did not load; staying on the JS backend", e)
        false
      }
      libraryState = ok
      return ok
    }
  }
}
`;

const PACKAGE_KT = (pkg) => `package ${pkg}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Generated by mobile/plugins/withGearKernelsPlugin.js — see GearKernelsModule. */
class GearKernelsPackage : ReactPackage {
  override fun createNativeModules(
      reactContext: ReactApplicationContext
  ): List<NativeModule> = listOf(GearKernelsModule(reactContext))

  override fun createViewManagers(
      reactContext: ReactApplicationContext
  ): List<ViewManager<*, *>> = emptyList()
}
`;

const GRADLE_MARKER = '// PAP-1694 gearkernels';
const GRADLE_BLOCK = `
    ${GRADLE_MARKER} — native preprocess kernels (mobile/plugins/withGearKernelsPlugin.js)
    buildFeatures {
        prefab true
    }
    externalNativeBuild {
        cmake {
            path "src/main/jni/CMakeLists.txt"
        }
    }
`;

// `android/` survives across `expo prebuild` runs unless --clean is passed, so
// an already-injected block from an older revision of this plugin has to be
// removed rather than skipped — otherwise the stale cmake path wins forever
// and the fix never reaches a build.  Exact strings, not a regex, so this can
// only ever delete something this plugin itself wrote.
const LEGACY_GRADLE_BLOCKS = [
  `
    ${GRADLE_MARKER} — native preprocess kernels (mobile/plugins/withGearKernelsPlugin.js)
    buildFeatures {
        prefab true
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
`,
];

function withGearKernelsPlugin(config) {
  // 1 + 2: C++ sources and CMakeLists into the android tree.
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const pkg = config.android?.package || 'com.gearcounter.app';
      const cppSrc = path.join(config.modRequest.projectRoot, 'cpp');
      const cppDst = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'cpp');
      fs.mkdirSync(cppDst, { recursive: true });

      for (const file of CPP_SOURCES) {
        let contents = fs.readFileSync(path.join(cppSrc, file), 'utf8');
        if (file === 'GearKernelsJni.cpp') {
          // JNI symbol names encode the fully-qualified Java class name.
          contents = contents.replace(
            /Java_com_gearcounter_app_GearKernelsModule_nativeInstall/g,
            `Java_${pkg.replace(/\./g, '_')}_GearKernelsModule_nativeInstall`,
          );
        }
        fs.writeFileSync(path.join(cppDst, file), contents);
      }
      fs.writeFileSync(path.join(cppDst, 'CMakeLists.txt'), KERNELS_CMAKE);

      // 2b: the app-level CMakeLists, in its own directory so that
      // ReactNative-application.cmake's `*.cpp` glob does not pick up our
      // sources in place of the framework's OnLoad.cpp.
      const jniDst = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'jni');
      fs.mkdirSync(jniDst, { recursive: true });
      const jniCMake = path.join(jniDst, 'CMakeLists.txt');
      if (fs.existsSync(jniCMake)) {
        const existing = fs.readFileSync(jniCMake, 'utf8');
        if (!existing.includes('withGearKernelsPlugin.js')) {
          throw new Error(
            '[withGearKernelsPlugin] android/app/src/main/jni/CMakeLists.txt exists and was ' +
            'not written by this plugin. It is the app\'s appmodules target — refusing to ' +
            'clobber it. Merge the add_subdirectory(../cpp) line into it by hand instead.');
        }
      }
      fs.writeFileSync(jniCMake, APP_CMAKE);

      // 4: Kotlin sources.
      const javaDir = path.join(
        config.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java', pkg.replace(/\./g, '/'),
      );
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(path.join(javaDir, 'GearKernelsModule.kt'), MODULE_KT(pkg));
      fs.writeFileSync(path.join(javaDir, 'GearKernelsPackage.kt'), PACKAGE_KT(pkg));

      return config;
    },
  ]);

  // 3: build.gradle wiring.
  config = withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;
    for (const legacy of LEGACY_GRADLE_BLOCKS) {
      contents = contents.split(legacy).join('');
    }
    if (!contents.includes(GRADLE_MARKER)) {
      contents = contents.replace(/^android \{\n/m, (m) => m + GRADLE_BLOCK);
      if (!contents.includes(GRADLE_MARKER)) {
        throw new Error(
          '[withGearKernelsPlugin] could not find the `android {` block in app/build.gradle');
      }
    }
    config.modResults.contents = contents;
    return config;
  });

  // 5: register the package.
  config = withMainApplication(config, (config) => {
    let contents = config.modResults.contents;
    const addLine = 'add(GearKernelsPackage())';
    if (!contents.includes(addLine)) {
      const anchor = '// add(MyReactNativePackage())';
      if (!contents.includes(anchor)) {
        throw new Error(
          '[withGearKernelsPlugin] MainApplication.kt has no getPackages() anchor to patch');
      }
      contents = contents.replace(anchor, `${anchor}\n              ${addLine}`);
    }
    config.modResults.contents = contents;
    return config;
  });

  return config;
}

module.exports = withGearKernelsPlugin;
