/**
 * PAP-1694 (option A) — Expo config plugin for the native preprocess kernels.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so every piece
 * of native wiring has to be reapplied from here.  This plugin:
 *
 *   1. copies mobile/cpp/*.{h,cpp} into android/app/src/main/cpp/
 *   2. writes android/app/src/main/cpp/CMakeLists.txt
 *   3. adds `buildFeatures { prefab true }` + `externalNativeBuild` to
 *      android/app/build.gradle
 *   4. writes GearKernelsModule.kt / GearKernelsPackage.kt
 *   5. registers GearKernelsPackage in MainApplication.kt
 *
 * Why our own kernels rather than react-native-fast-opencv's: that binding
 * exposes no CLAHE at all and its cv::Canny is a different algorithm from ours
 * (IoU 0.437 against the JS edge map).  Routing preprocess through it would
 * change the edge map that the whole detect stage consumes, i.e. an accuracy
 * change requiring a corpus re-baseline — which is what AC5 forbids.  The C++
 * here is a line-by-line port of src/algorithm/imageUtils.js and is verified
 * byte-identical over the corpus by __tests__/pap1694.native-parity.mjs.
 * fast-opencv stays linked for the detect port (PAP-1696), which needs
 * cv::dft.
 */
const {
  withDangerousMod,
  withAppBuildGradle,
  withMainApplication,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const CPP_SOURCES = [
  'gear_kernels.h',
  'gear_kernels.cpp',
  'GearKernelsJsi.h',
  'GearKernelsJsi.cpp',
  'GearKernelsJni.cpp',
];

// -ffp-contract=off is load-bearing, not hygiene: with contraction enabled
// clang is free to fuse the `a*b + c*d` terms of the CLAHE bilinear blend into
// FMAs, which keeps more intermediate precision than the JS does and shifts
// Math.round by one at ties.  That alone would break byte parity.
const CMAKE = `# Generated by mobile/plugins/withGearKernelsPlugin.js — do not edit in place.
cmake_minimum_required(VERSION 3.13)
project(gearkernels CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Must match the flags mobile/__tests__/pap1694.native-parity.mjs proves parity
# under.  See the note in the plugin source.
add_compile_options(-ffp-contract=off -fno-fast-math)

find_package(ReactAndroid REQUIRED CONFIG)

add_library(gearkernels SHARED
  gear_kernels.cpp
  GearKernelsJsi.cpp
  GearKernelsJni.cpp
)

target_include_directories(gearkernels PRIVATE \${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(gearkernels
  ReactAndroid::jsi
  android
  log
)
`;

const MODULE_KT = (pkg) => `package ${pkg}

import android.util.Log
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * PAP-1694 — installs the native preprocess kernels onto the JS runtime.
 *
 * Generated by mobile/plugins/withGearKernelsPlugin.js.
 *
 * \`install()\` is a blocking synchronous method because it has to run on the JS
 * thread with the runtime alive: it hands the jsi::Runtime pointer to C++,
 * which sets \`globalThis.__gearKernels\`.  JS calls it once, lazily, from
 * src/algorithm/nativeKernels.js and falls back to the pure-JS backend if it
 * returns false — a device without the .so must still count teeth.
 */
class GearKernelsModule(reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = NAME

  private external fun nativeInstall(jsiRuntimeRef: Long)

  @ReactMethod(isBlockingSynchronousMethod = true)
  fun install(): Boolean {
    if (!loadLibraryOnce()) return false
    return try {
      val ref = reactApplicationContext.javaScriptContextHolder?.get() ?: 0L
      if (ref == 0L) {
        Log.w(NAME, "no jsi runtime pointer available; staying on the JS backend")
        return false
      }
      nativeInstall(ref)
      true
    } catch (e: Throwable) {
      Log.e(NAME, "install failed; staying on the JS backend", e)
      false
    }
  }

  companion object {
    private const val NAME = "GearKernels"

    // Loaded lazily rather than in a static initialiser: an UnsatisfiedLinkError
    // in \`init\` would surface as ExceptionInInitializerError at module
    // construction and take the whole native-module registry down with it.
    @Volatile private var libraryState: Boolean? = null

    @Synchronized
    private fun loadLibraryOnce(): Boolean {
      libraryState?.let { return it }
      val ok = try {
        System.loadLibrary("gearkernels")
        true
      } catch (e: Throwable) {
        Log.e(NAME, "libgearkernels.so did not load; staying on the JS backend", e)
        false
      }
      libraryState = ok
      return ok
    }
  }
}
`;

const PACKAGE_KT = (pkg) => `package ${pkg}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Generated by mobile/plugins/withGearKernelsPlugin.js — see GearKernelsModule. */
class GearKernelsPackage : ReactPackage {
  override fun createNativeModules(
      reactContext: ReactApplicationContext
  ): List<NativeModule> = listOf(GearKernelsModule(reactContext))

  override fun createViewManagers(
      reactContext: ReactApplicationContext
  ): List<ViewManager<*, *>> = emptyList()
}
`;

const GRADLE_MARKER = '// PAP-1694 gearkernels';
const GRADLE_BLOCK = `
    ${GRADLE_MARKER} — native preprocess kernels (mobile/plugins/withGearKernelsPlugin.js)
    buildFeatures {
        prefab true
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
`;

function withGearKernelsPlugin(config) {
  // 1 + 2: C++ sources and CMakeLists into the android tree.
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const pkg = config.android?.package || 'com.gearcounter.app';
      const cppSrc = path.join(config.modRequest.projectRoot, 'cpp');
      const cppDst = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'cpp');
      fs.mkdirSync(cppDst, { recursive: true });

      for (const file of CPP_SOURCES) {
        let contents = fs.readFileSync(path.join(cppSrc, file), 'utf8');
        if (file === 'GearKernelsJni.cpp') {
          // JNI symbol names encode the fully-qualified Java class name.
          contents = contents.replace(
            /Java_com_gearcounter_app_GearKernelsModule_nativeInstall/g,
            `Java_${pkg.replace(/\./g, '_')}_GearKernelsModule_nativeInstall`,
          );
        }
        fs.writeFileSync(path.join(cppDst, file), contents);
      }
      fs.writeFileSync(path.join(cppDst, 'CMakeLists.txt'), CMAKE);

      // 4: Kotlin sources.
      const javaDir = path.join(
        config.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java', pkg.replace(/\./g, '/'),
      );
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(path.join(javaDir, 'GearKernelsModule.kt'), MODULE_KT(pkg));
      fs.writeFileSync(path.join(javaDir, 'GearKernelsPackage.kt'), PACKAGE_KT(pkg));

      return config;
    },
  ]);

  // 3: build.gradle wiring.
  config = withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;
    if (!contents.includes(GRADLE_MARKER)) {
      contents = contents.replace(/^android \{\n/m, (m) => m + GRADLE_BLOCK);
      if (!contents.includes(GRADLE_MARKER)) {
        throw new Error(
          '[withGearKernelsPlugin] could not find the `android {` block in app/build.gradle');
      }
    }
    config.modResults.contents = contents;
    return config;
  });

  // 5: register the package.
  config = withMainApplication(config, (config) => {
    let contents = config.modResults.contents;
    const addLine = 'add(GearKernelsPackage())';
    if (!contents.includes(addLine)) {
      const anchor = '// add(MyReactNativePackage())';
      if (!contents.includes(anchor)) {
        throw new Error(
          '[withGearKernelsPlugin] MainApplication.kt has no getPackages() anchor to patch');
      }
      contents = contents.replace(anchor, `${anchor}\n              ${addLine}`);
    }
    config.modResults.contents = contents;
    return config;
  });

  return config;
}

module.exports = withGearKernelsPlugin;
