import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { decode: jpegDecode } = require('jpeg-js');
globalThis.__PAP1898_TRACE = 1;
const gc = await import('/home/paperclip/.paperclip/instances/default/projects/2a07d193-9a49-4cbd-ab0b-486be0ae801b/gear-camera-app/mobile/src/algorithm/gearCounter.js');
const { bilinearDownsampleRgba, __test } = gc;
const iu = await import('/home/paperclip/.paperclip/instances/default/projects/2a07d193-9a49-4cbd-ab0b-486be0ae801b/gear-camera-app/mobile/src/algorithm/imageUtils.js');
const { applyCircularMask } = iu;
const pp = await import('/home/paperclip/.paperclip/instances/default/projects/2a07d193-9a49-4cbd-ab0b-486be0ae801b/gear-camera-app/mobile/src/algorithm/preprocess.js');
console.log('has pap1898SilhouetteFit:', typeof __test.pap1898SilhouetteFit);
const photo='/home/paperclip/.paperclip/instances/default/projects/2a07d193-9a49-4cbd-ab0b-486be0ae801b/gear-camera-app/debug-reports/pap1897_fp5_b153_session_2026-09-11/f5886a846722_cropped.jpg';
const raw = jpegDecode(fs.readFileSync(photo), { useTArray: true });
const ds = bilinearDownsampleRgba(raw.data, raw.width, raw.height, 900);
const { rgba, width: w, height: h } = ds;
applyCircularMask(rgba, w, h, (w-1)/2, (h-1)/2, 0.49*Math.min(w,h));
const { gray, enhanced, edges } = pp.preprocess(rgba, w, h);
const fit = __test.pap1898SilhouetteFit(edges, w, h);
console.log('fit:', fit.coverage.toFixed(2), fit.fit && `${fit.fit.cx.toFixed(0)},${fit.fit.cy.toFixed(0)},r${fit.fit.r.toFixed(0)}`);
const c = __test.findGearCenter(gray, enhanced, edges, w, h, Infinity, {hit:false});
console.log('center:', c.cx, c.cy, c.radius, c.method);
