/**
 * Build metadata — generated by scripts/build-release.sh.
 * DO NOT edit by hand; run the build script to update.
 */
export const BUILD_VERSION = '1.0.0';
export const BUILD_NUMBER  = 143;
export const BUILD_DATE    = '2026-08-23 23:57';  // YYYY-MM-DD HH:MM
export const BUILD_LABEL   = 'v1.0.0 (143) · 2026-08-23 23:57';
