#!/usr/bin/env bash
# gradle-constraints.sh — shared build-host thread constraints for
#                         scripts/build-debug.sh and scripts/build-release.sh.
#                         Sourced, not executed.
#
# PAP-1661. The b135 release build first died with
#
#     unable to create native thread: possibly out of memory or process/
#     resource limits reached
#
# The message points at memory; the cause is a thread cap. Every agent on this
# build host shares one `paperclip.service` cgroup with `pids.max=600`.
# `pids.current` sits around 300-430 whenever other agents are awake, and
# `pids.events` already recorded `max 8` — the cap had been hit eight times
# before anyone looked. An unconstrained Gradle build (parallel workers + a
# forked daemon JVM + a Kotlin daemon + Metro's node workers, every one of them
# sizing its internal pools off 8 CPUs) exhausts whatever headroom is left.
# Whether it fails is a function of how many other agents happen to be awake,
# which makes it intermittent and expensive to rediscover.
#
# The fix originally lived in `mobile/android/gradle.properties`. That is the
# wrong home: android/ is gitignored AND regenerated by `expo prebuild`, so the
# settings existed on exactly one machine until the next prebuild deleted them.
#
# Durability now has three independent halves, deliberately overlapping because
# the failure mode is intermittent:
#
#   1. this file — passed on the ./gradlew command line, so it holds even
#      against a stale or hand-edited android/ tree that no prebuild touched;
#   2. mobile/plugins/withBuildHostGradleProps.js — re-writes the same values
#      into android/gradle.properties on every `expo prebuild`, so a bare
#      `./gradlew assembleDebug` outside these scripts is also covered;
#   3. mobile/metro.config.js — pins Metro's worker count, which neither of the
#      above can reach (JVM -XX flags do not bound Node child processes).
#
# Keep the values in (1) and (2) in sync.
#
# Verified empirically on 2026-08-22 with android/gradle.properties stripped of
# all tuning: an init-script probe on `./gradlew help` reported
# availableProcessors=2, maxWorkerCount=1, parallel=false, watchFileSystem
# DISABLED, kotlin strategy=in-process, kotlin.incremental=false — i.e. every
# constraint below survives the CLI-only path with no help from the generated
# gradle.properties.
#
# Set GRADLE_UNCONSTRAINED=1 to skip all of this — for a build host that is not
# thread-capped, where a 1-worker daemon-less build is pure pessimisation.

# Daemon JVM args. -XX:ActiveProcessorCount=2 is the load-bearing one: without
# it the JVM sizes its GC threads, JIT compiler threads and
# ForkJoinPool.commonPool off all 8 CPUs, and does so in *every* JVM the build
# forks. -Dorg.gradle.jvmargs on the command line is honoured by Gradle 8.14.3
# (confirmed by the probe above); it is not merely a system property.
GRADLE_CONSTRAINT_JVMARGS="-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ActiveProcessorCount=2"

# Populated by gradle_constraint_flags; expand as "${GRADLE_CONSTRAINT_FLAGS[@]}".
GRADLE_CONSTRAINT_FLAGS=()

# Fill GRADLE_CONSTRAINT_FLAGS and echo a one-line summary.
gradle_constraint_flags() {
  if [[ -n "${GRADLE_UNCONSTRAINED:-}" ]]; then
    GRADLE_CONSTRAINT_FLAGS=()
    echo "[build] Gradle thread constraints DISABLED (GRADLE_UNCONSTRAINED is set)."
    return 0
  fi

  GRADLE_CONSTRAINT_FLAGS=(
    # No long-lived daemon left holding threads between builds. Gradle still
    # forks one single-use daemon to honour the JVM args below.
    --no-daemon
    # One project at a time.
    --no-parallel
    # One worker process at a time.
    --max-workers=1
    # The file-system watcher spawns inotify threads per watched hierarchy.
    --no-watch-fs
    -Dorg.gradle.jvmargs="$GRADLE_CONSTRAINT_JVMARGS"
    # Compile Kotlin inside the Gradle process rather than forking a Kotlin
    # daemon JVM, which is an entire extra process with its own thread pools.
    -Pkotlin.compiler.execution.strategy=in-process
    # Incremental compilation keeps extra daemon-side state and workers, and
    # android/ is regenerated by prebuild anyway so there is little to reuse.
    -Pkotlin.incremental=false
  )

  echo "[build] Gradle thread constraints: --no-daemon --no-parallel --max-workers=1 --no-watch-fs, jvmargs='$GRADLE_CONSTRAINT_JVMARGS', kotlin in-process (PAP-1661)"
  if [[ -r /sys/fs/cgroup/system.slice/paperclip.service/pids.current ]]; then
    echo "[build] cgroup pids: $(cat /sys/fs/cgroup/system.slice/paperclip.service/pids.current)/$(cat /sys/fs/cgroup/system.slice/paperclip.service/pids.max 2>/dev/null || echo '?') in use at build start"
  fi
}
