#!/usr/bin/env bash
# sentry-options.sh — stamp per-build release/dist into mobile/sentry.options.json
#                     for scripts/build-debug.sh and scripts/build-release.sh.
#                     Sourced, not executed.
#
# PAP-1662. src/sentry.js now passes `autoInitializeNativeSdk: false` in release
# builds, so the native SDK's options come solely from the asset copy of
# mobile/sentry.options.json that RNSentrySDK.init reads. Previously the JS
# re-init overwrote them, which is what made `release: BUILD_LABEL` apply to
# native-origin events too.
#
# Without this stamp, sentry-android falls back to its default release,
# `packageName@versionName+versionCode`. android/app/build.gradle pins
# `versionCode 1` / `versionName "1.0.0"` and neither build script bumps them,
# so EVERY build would report native crashes under the single release
# `com.gearcounter.app@1.0.0+1` — destroying build attribution for exactly the
# JVM/NDK/ANR telemetry PAP-1653 was added to capture.
#
# `release` and `dist` are read by RNSentryStart.java (options.setRelease /
# options.setDist), so the JSON is the right place to carry them.
#
# mobile/sentry.options.json is gitignored and regenerated by `expo prebuild`
# from the plugin config in mobile/app.config.js. prebuild drops these two keys
# again (it cannot know the build number), which is fine: this stamp runs on
# every build and re-adds them before Gradle copies the file into assets/.

# stamp_sentry_options <options-json-path> <release> <dist>
#
# Merges release/dist into the existing options file, preserving every other
# key. Fails loudly if the file is missing — a silent skip here would ship an
# APK whose native crashes are misattributed, which is the whole failure mode
# this guard exists to prevent.
stamp_sentry_options() {
  local options_file="$1" release="$2" dist="$3"

  if [[ ! -f "$options_file" ]]; then
    echo "[build] ERROR: $options_file is missing." >&2
    echo "[build] It is generated by the @sentry/react-native/expo plugin." >&2
    echo "[build] Re-run 'npx expo prebuild -p android' from mobile/ with .env sourced." >&2
    return 1
  fi

  SENTRY_OPTIONS_FILE="$options_file" \
  SENTRY_STAMP_RELEASE="$release" \
  SENTRY_STAMP_DIST="$dist" \
  node -e '
    const fs = require("fs");
    const file = process.env.SENTRY_OPTIONS_FILE;
    const options = JSON.parse(fs.readFileSync(file, "utf8"));
    options.release = process.env.SENTRY_STAMP_RELEASE;
    options.dist = process.env.SENTRY_STAMP_DIST;
    fs.writeFileSync(file, JSON.stringify(options, null, 2) + "\n");
  ' || {
    echo "[build] ERROR: failed to stamp release/dist into $options_file" >&2
    return 1
  }

  echo "[build] Stamped release/dist into $options_file"
}
