#!/usr/bin/env bash
# build-debug.sh — Stamp build metadata, run Gradle debug build, archive APK.
#
# Usage: ./scripts/build-debug.sh
# Run from the repo root.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOBILE_DIR="$REPO_ROOT/mobile"
ANDROID_DIR="$MOBILE_DIR/android"
BUILD_INFO="$MOBILE_DIR/src/buildInfo.js"
TEST_BUILDS_DIR="$REPO_ROOT/test-builds"
README="$TEST_BUILDS_DIR/README.md"

# ── Derive version + build number ────────────────────────────────────────────
VERSION=$(node -p "require('$MOBILE_DIR/package.json').version")
BUILD_DATE=$(date +%Y-%m-%d)
BUILD_TS=$(date +%Y%m%d-%H%M%S)

# Increment build number from current buildInfo.js
PREV_BUILD=$(grep "BUILD_NUMBER" "$BUILD_INFO" | grep -oE '[0-9]+' | head -1)
BUILD_NUMBER=$(( ${PREV_BUILD:-0} + 1 ))

BUILD_LABEL="v${VERSION} (${BUILD_NUMBER}) · ${BUILD_DATE}"

echo "[build] Version: $VERSION  Build: $BUILD_NUMBER  Date: $BUILD_DATE"

# ── Stamp buildInfo.js ────────────────────────────────────────────────────────
cat > "$BUILD_INFO" <<EOF
/**
 * Build metadata — generated by scripts/build-debug.sh.
 * DO NOT edit by hand; run the build script to update.
 */
export const BUILD_VERSION = '$VERSION';
export const BUILD_NUMBER  = $BUILD_NUMBER;
export const BUILD_DATE    = '$BUILD_DATE';
export const BUILD_LABEL   = '$BUILD_LABEL';
EOF

echo "[build] Stamped $BUILD_INFO"

# ── Run Gradle assembleDebug ──────────────────────────────────────────────────
cd "$ANDROID_DIR"
echo "[build] Running assembleDebug…"
./gradlew assembleDebug

APK_SRC=$(find "$ANDROID_DIR/app/build/outputs/apk/debug" -name "*.apk" | head -1)
if [[ -z "$APK_SRC" ]]; then
  echo "[build] ERROR: No APK found after build" >&2
  exit 1
fi

# ── Archive APK ───────────────────────────────────────────────────────────────
APK_NAME="gear-camera-debug-${BUILD_DATE}-b${BUILD_NUMBER}.apk"
APK_DEST="$TEST_BUILDS_DIR/$APK_NAME"
cp "$APK_SRC" "$APK_DEST"
APK_SIZE_MB=$(du -m "$APK_DEST" | cut -f1)

echo "[build] APK → $APK_DEST (${APK_SIZE_MB}MB)"

# ── Update test-builds/README.md ──────────────────────────────────────────────
# Append a new row to the table.
TIMESTAMP_FULL=$(date +"%Y-%m-%d %H:%M")
NEW_ROW="| $TIMESTAMP_FULL | $APK_NAME (${APK_SIZE_MB}MB) | b${BUILD_NUMBER} | local |"

# Insert row after the table header line (the line starting with "| Date")
python3 - "$README" "$NEW_ROW" <<'PYEOF'
import sys, re
path, row = sys.argv[1], sys.argv[2]
with open(path) as f:
    content = f.read()
# Find the separator line (---|---) and insert after it
lines = content.splitlines(keepends=True)
result = []
inserted = False
for i, line in enumerate(lines):
    result.append(line)
    if not inserted and re.match(r'\|[-| ]+\|', line):
        result.append(row + '\n')
        inserted = True
if not inserted:
    result.append(row + '\n')
with open(path, 'w') as f:
    f.writelines(result)
print(f"[build] Updated {path}")
PYEOF

echo "[build] Done. Build label: $BUILD_LABEL"
