#!/usr/bin/env bash
# build-debug.sh — Stamp build metadata, run Gradle debug build, archive APK,
#                   upload source maps to Sentry, and publish APK to GitHub
#                   Releases.
#
# Usage: ./scripts/build-debug.sh
# Run from the repo root.
#
# Env (loaded from .env if present):
#   - GITHUB_PAT / GITHUB_TOKEN  Operator-side PAT for `gh release create`.
#                                Only used here on the build host — NEVER
#                                shipped in the APK (PAP-1543/PAP-1463).
#   - SENTRY_AUTH_TOKEN          sentry-cli source-map upload auth.
#   - SENTRY_ORG / SENTRY_PROJECT  org/project slugs for sentry-cli.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOBILE_DIR="$REPO_ROOT/mobile"
ANDROID_DIR="$MOBILE_DIR/android"
BUILD_INFO="$MOBILE_DIR/src/buildInfo.js"
TEST_BUILDS_DIR="$REPO_ROOT/test-builds"
README="$TEST_BUILDS_DIR/README.md"
GH_REPO="claudegoogl-sudo/gear-camera-app"

# ── Load .env if present ─────────────────────────────────────────────────────
if [[ -f "$REPO_ROOT/.env" ]]; then
  set -a
  source "$REPO_ROOT/.env"
  set +a
fi

# Resolve GitHub token for release uploads (operator-side only — the on-device
# upload path moved to Sentry in PAP-1543).  EXPO_PUBLIC_GITHUB_TOKEN is no
# longer the canonical name but kept here for backwards-compat with older .env
# files.
GH_TOKEN="${GITHUB_PAT:-${GITHUB_TOKEN:-${EXPO_PUBLIC_GITHUB_TOKEN:-}}}"

# ── Derive version + build number ────────────────────────────────────────────
VERSION=$(node -p "require('$MOBILE_DIR/package.json').version")
BUILD_DATE=$(date +"%Y-%m-%d %H:%M")
BUILD_TS=$(date +%Y%m%d-%H%M%S)

# Increment build number from current buildInfo.js
PREV_BUILD=$(grep "BUILD_NUMBER" "$BUILD_INFO" | grep -oE '[0-9]+' | head -1)
BUILD_NUMBER=$(( ${PREV_BUILD:-0} + 1 ))

BUILD_LABEL="v${VERSION} (${BUILD_NUMBER}) · ${BUILD_DATE}"

echo "[build] Version: $VERSION  Build: $BUILD_NUMBER  Timestamp: $BUILD_DATE"

# ── Stamp buildInfo.js ────────────────────────────────────────────────────────
cat > "$BUILD_INFO" <<EOF
/**
 * Build metadata — generated by scripts/build-debug.sh.
 * DO NOT edit by hand; run the build script to update.
 */
export const BUILD_VERSION = '$VERSION';
export const BUILD_NUMBER  = $BUILD_NUMBER;
export const BUILD_DATE    = '$BUILD_DATE';  // YYYY-MM-DD HH:MM
export const BUILD_LABEL   = '$BUILD_LABEL';
EOF

echo "[build] Stamped $BUILD_INFO"

# ── Run Gradle assembleDebug ──────────────────────────────────────────────────
cd "$ANDROID_DIR"

# Ship only the two physical-device ABIs. x86/x86_64 are emulator-only, cannot
# execute on any test handset, and cost ~94MB of the artifact. QA validation is
# physical-device only (PAP-1637). Passed on the CLI rather than edited into
# android/gradle.properties because that directory is generated and gitignored.
ABIS="armeabi-v7a,arm64-v8a"

# PAP-1653: applying sentry.gradle (needed for the sentry.options.json → assets
# copy) also turns on its Gradle-side source-map auto-upload. Keep the explicit
# sentry-cli step below as the single upload path so upload behaviour is
# unchanged from b134.
export SENTRY_DISABLE_AUTO_UPLOAD=true

echo "[build] Running assembleDebug (ABIs: $ABIS)…"
./gradlew assembleDebug -PreactNativeArchitectures="$ABIS"

APK_SRC=$(find "$ANDROID_DIR/app/build/outputs/apk/debug" -name "*.apk" | head -1)
if [[ -z "$APK_SRC" ]]; then
  echo "[build] ERROR: No APK found after build" >&2
  exit 1
fi

# ── Verify the Sentry DSN reached the packaged bundle (PAP-1650) ─────────────
# `.env` lives at the REPO root, but the Expo project root is `mobile/`, so
# Expo CLI never auto-loads it. The DSN reaches the bundle only via the
# `set -a; source .env` step above. A bare `./gradlew assemble*` therefore
# produces an APK where sentry.js sees an empty DSN, never calls Sentry.init,
# and every telemetry path is dead — debug reports, training upload, chainring
# events and native crash handling. That is how b133 shipped dark. Assert
# against the artifact, not the environment, because only the artifact ships.
assert_sentry_dsn_bundled() {
  local apk="$1" tmp
  if [[ -z "${EXPO_PUBLIC_SENTRY_DSN:-}" ]]; then
    echo "[build] ERROR: EXPO_PUBLIC_SENTRY_DSN is unset — this build would ship with all" >&2
    echo "[build] telemetry disabled. Set it in $REPO_ROOT/.env (repo root, not mobile/)." >&2
    exit 1
  fi
  tmp=$(mktemp -d)
  if unzip -o -q "$apk" assets/index.android.bundle -d "$tmp" \
     && grep -q -a -F "$EXPO_PUBLIC_SENTRY_DSN" "$tmp/assets/index.android.bundle"; then
    rm -rf "$tmp"
    echo "[build] Verified Sentry DSN is baked into the packaged JS bundle"
  else
    rm -rf "$tmp"
    echo "[build] ERROR: EXPO_PUBLIC_SENTRY_DSN is set but is absent from the packaged" >&2
    echo "[build] bundle — the artifact would ship telemetry-dead. Refusing to publish." >&2
    exit 1
  fi
}
assert_sentry_dsn_bundled "$APK_SRC"

# ── Verify native Sentry is configured (PAP-1653) ─────────────────────────────
# The check above only proves JS can reach Sentry. The native SDK is started
# separately by `RNSentrySDK.init(this)` in MainApplication.onCreate, which
# reads its DSN from `assets/sentry.options.json`. Without that asset, JVM/NDK
# crashes and ANRs that happen before the JS bundle loads have no telemetry
# path. Both halves are produced by the @sentry/react-native Expo plugin at
# `expo prebuild` time, so a stale `android/` tree silently drops them —
# assert against the artifact, same as the bundle check.
#
# NOTE: `io.sentry.dsn` manifest meta-data is deliberately NOT used. The SDK
# ships `io.sentry.auto-init=false` in its own manifest, so sentry-android's
# SentryInitProvider ignores any DSN meta-data. The options-file path is the
# only one that actually starts the native SDK.
assert_sentry_native_configured() {
  local apk="$1" main_application tmp
  tmp=$(mktemp -d)
  if unzip -o -q "$apk" assets/sentry.options.json -d "$tmp" \
     && grep -q -a -F "$EXPO_PUBLIC_SENTRY_DSN" "$tmp/assets/sentry.options.json"; then
    rm -rf "$tmp"
    echo "[build] Verified Sentry DSN is baked into the packaged native options file"
  else
    rm -rf "$tmp"
    echo "[build] ERROR: assets/sentry.options.json is missing from the APK or does not" >&2
    echo "[build] carry the DSN — native crashes before JS init would go unreported." >&2
    echo "[build] Re-run 'npx expo prebuild -p android' from mobile/ with .env sourced." >&2
    exit 1
  fi

  # The options file is inert unless MainApplication actually starts the SDK.
  main_application=$(find "$ANDROID_DIR/app/src/main/java" -name 'MainApplication.kt' | head -1)
  if [[ -z "$main_application" ]] || ! grep -q 'RNSentrySDK.init' "$main_application"; then
    echo "[build] ERROR: MainApplication.kt does not call RNSentrySDK.init — the packaged" >&2
    echo "[build] sentry.options.json would never be read. Re-run 'npx expo prebuild'." >&2
    exit 1
  fi
  echo "[build] Verified MainApplication starts the native Sentry SDK"
}
assert_sentry_native_configured "$APK_SRC"

# ── Sentry source-map upload (PAP-1543) ───────────────────────────────────────
# Lets the Sentry stack trace UI map minified bundle frames back to source.
# Non-fatal if creds are missing or the upload fails — the APK still ships.
SENTRY_CLI="$MOBILE_DIR/node_modules/@sentry/cli/bin/sentry-cli"
if [[ -n "${SENTRY_AUTH_TOKEN:-}" && -n "${SENTRY_ORG:-}" && -n "${SENTRY_PROJECT:-}" && -x "$SENTRY_CLI" ]]; then
  echo "[build] Uploading source maps to Sentry (release=$BUILD_LABEL)…"
  (
    cd "$MOBILE_DIR"
    SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN" \
    SENTRY_ORG="$SENTRY_ORG" \
    SENTRY_PROJECT="$SENTRY_PROJECT" \
    "$SENTRY_CLI" sourcemaps upload \
      --release "$BUILD_LABEL" \
      --strip-prefix "$MOBILE_DIR" \
      "$ANDROID_DIR/app/build/generated/assets/createBundleDebugJsAndAssets" \
      "$ANDROID_DIR/app/build/intermediates/sourcemaps/react/debug" 2>&1
  ) || echo "[build] WARNING: Sentry sourcemap upload failed (non-fatal)." >&2
else
  echo "[build] Skipping Sentry sourcemap upload (SENTRY_AUTH_TOKEN / SENTRY_ORG / SENTRY_PROJECT or sentry-cli missing)."
fi

# ── Archive APK ───────────────────────────────────────────────────────────────
APK_NAME="gear-camera-debug-${BUILD_DATE}-b${BUILD_NUMBER}.apk"
APK_DEST="$TEST_BUILDS_DIR/$APK_NAME"
cp "$APK_SRC" "$APK_DEST"
APK_SIZE_MB=$(du -m "$APK_DEST" | cut -f1)

echo "[build] APK → $APK_DEST (${APK_SIZE_MB}MB)"

# ── Upload to GitHub Releases ────────────────────────────────────────────────
DOWNLOAD_LINK="local"
TAG="b${BUILD_NUMBER}"
# Sanitize APK name for upload — GitHub strips/replaces both spaces and colons
# in release asset filenames, so the README link must use the same dots.
UPLOAD_APK_NAME="${APK_NAME// /.}"
UPLOAD_APK_NAME="${UPLOAD_APK_NAME//:/.}"

if [[ -n "$GH_TOKEN" ]]; then
  echo "[build] Uploading to GitHub Releases as tag $TAG…"
  if GITHUB_TOKEN="$GH_TOKEN" gh release create "$TAG" \
       --repo "$GH_REPO" \
       --title "Debug Build b${BUILD_NUMBER}" \
       --notes "Build b${BUILD_NUMBER} — v${VERSION} — ${BUILD_DATE}" \
       "$APK_DEST#$UPLOAD_APK_NAME" 2>&1; then
    DOWNLOAD_LINK="[Download](https://github.com/$GH_REPO/releases/download/$TAG/$UPLOAD_APK_NAME)"
    echo "[build] Release $TAG uploaded successfully."
  else
    echo "[build] WARNING: GitHub release upload failed. Build succeeded locally." >&2
  fi
else
  echo "[build] WARNING: No GitHub token found (set GITHUB_PAT or EXPO_PUBLIC_GITHUB_TOKEN in .env). Skipping release upload." >&2
fi

# ── Update test-builds/README.md ──────────────────────────────────────────────
# Append a new row to the table.
TIMESTAMP_FULL=$(date +"%Y-%m-%d %H:%M")
NEW_ROW="| $TIMESTAMP_FULL | $APK_NAME (${APK_SIZE_MB}MB) | b${BUILD_NUMBER} | $DOWNLOAD_LINK |"

# Insert row after the table header line (the line starting with "| Date")
python3 - "$README" "$NEW_ROW" <<'PYEOF'
import sys, re
path, row = sys.argv[1], sys.argv[2]
with open(path) as f:
    content = f.read()
# Find the separator line (---|---) and insert after it
lines = content.splitlines(keepends=True)
result = []
inserted = False
for i, line in enumerate(lines):
    result.append(line)
    if not inserted and re.match(r'\|[-| ]+\|', line):
        result.append(row + '\n')
        inserted = True
if not inserted:
    result.append(row + '\n')
with open(path, 'w') as f:
    f.writelines(result)
print(f"[build] Updated {path}")
PYEOF

echo "[build] Done. Build label: $BUILD_LABEL"
