#!/usr/bin/env bash
# build-debug.sh — Stamp build metadata, run Gradle debug build, archive APK,
#                   upload source maps to Sentry, and publish APK to GitHub
#                   Releases.
#
# Usage: ./scripts/build-debug.sh
# Run from the repo root.
#
# Env (loaded from .env if present):
#   - GITHUB_PAT / GITHUB_TOKEN  Operator-side PAT for `gh release create`.
#                                Only used here on the build host — NEVER
#                                shipped in the APK (PAP-1543/PAP-1463).
#                                Optional: a token that does not authenticate is
#                                ignored in favour of the `gh` keyring login.
#   - SKIP_RELEASE_UPLOAD        Set to build a deliberately local-only artifact.
#   - SENTRY_AUTH_TOKEN          sentry-cli source-map upload auth.
#   - SENTRY_ORG / SENTRY_PROJECT  org/project slugs for sentry-cli.
#
# Exits non-zero if the APK cannot be published (PAP-1655).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOBILE_DIR="$REPO_ROOT/mobile"
ANDROID_DIR="$MOBILE_DIR/android"
BUILD_INFO="$MOBILE_DIR/src/buildInfo.js"
TEST_BUILDS_DIR="$REPO_ROOT/test-builds"
README="$TEST_BUILDS_DIR/README.md"

source "$REPO_ROOT/scripts/lib/gh-release.sh"
source "$REPO_ROOT/scripts/lib/gradle-constraints.sh"

# ── Load .env if present ─────────────────────────────────────────────────────
if [[ -f "$REPO_ROOT/.env" ]]; then
  set -a
  source "$REPO_ROOT/.env"
  set +a
fi

# Resolve publishing credentials up front (PAP-1655). Operator-side only — the
# on-device upload path moved to Sentry in PAP-1543.
gh_preflight_auth

# ── Derive version + build number ────────────────────────────────────────────
VERSION=$(node -p "require('$MOBILE_DIR/package.json').version")
BUILD_DATE=$(date +"%Y-%m-%d %H:%M")
BUILD_TS=$(date +%Y%m%d-%H%M%S)

# Increment build number from current buildInfo.js
PREV_BUILD=$(grep "BUILD_NUMBER" "$BUILD_INFO" | grep -oE '[0-9]+' | head -1)
BUILD_NUMBER=$(( ${PREV_BUILD:-0} + 1 ))

BUILD_LABEL="v${VERSION} (${BUILD_NUMBER}) · ${BUILD_DATE}"

echo "[build] Version: $VERSION  Build: $BUILD_NUMBER  Timestamp: $BUILD_DATE"

# ── Stamp buildInfo.js ────────────────────────────────────────────────────────
cat > "$BUILD_INFO" <<EOF
/**
 * Build metadata — generated by scripts/build-debug.sh.
 * DO NOT edit by hand; run the build script to update.
 */
export const BUILD_VERSION = '$VERSION';
export const BUILD_NUMBER  = $BUILD_NUMBER;
export const BUILD_DATE    = '$BUILD_DATE';  // YYYY-MM-DD HH:MM
export const BUILD_LABEL   = '$BUILD_LABEL';
EOF

echo "[build] Stamped $BUILD_INFO"

# ── Pin a Gradle-compatible JDK ───────────────────────────────────────────────
# The scripts used to inherit whatever `java` the host defaulted to. On
# 2026-08-22 that default moved to JDK 25 and every build died at
# `Error resolving plugin [id: 'com.facebook.react.settings'] > 25.0.3` —
# Gradle 8.14.3 and the React Native Gradle plugin do not support 25. Resolve a
# supported JDK explicitly so the toolchain cannot drift underneath us again.
# An operator-set JAVA_HOME still wins, so this is overridable.
if [[ -z "${JAVA_HOME:-}" ]]; then
  for candidate in /usr/lib/jvm/java-17-openjdk-amd64 /usr/lib/jvm/java-21-openjdk-amd64; do
    if [[ -x "$candidate/bin/java" ]]; then
      export JAVA_HOME="$candidate"
      break
    fi
  done
fi
if [[ -z "${JAVA_HOME:-}" ]]; then
  echo "[build] ERROR: no supported JDK found. Gradle 8.14.3 needs JDK 17 or 21;" >&2
  echo "[build] the host default is $(java -version 2>&1 | head -1). Set JAVA_HOME." >&2
  exit 1
fi
export PATH="$JAVA_HOME/bin:$PATH"
echo "[build] JDK: $("$JAVA_HOME/bin/java" -version 2>&1 | head -1) ($JAVA_HOME)"

# ── Run Gradle assembleDebug ──────────────────────────────────────────────────
cd "$ANDROID_DIR"

# Ship only the two physical-device ABIs. x86/x86_64 are emulator-only, cannot
# execute on any test handset, and cost ~94MB of the artifact. QA validation is
# physical-device only (PAP-1637). Passed on the CLI rather than edited into
# android/gradle.properties because that directory is generated and gitignored.
ABIS="armeabi-v7a,arm64-v8a"

# PAP-1653: applying sentry.gradle (needed for the sentry.options.json → assets
# copy) also turns on its Gradle-side source-map auto-upload. Keep the explicit
# sentry-cli step below as the single upload path so upload behaviour is
# unchanged from b134.
export SENTRY_DISABLE_AUTO_UPLOAD=true

# Constrain the build's thread footprint (PAP-1661). These used to live in
# android/gradle.properties, which is gitignored and wiped by `expo prebuild`;
# passing them here makes them version-controlled and prebuild-proof.
gradle_constraint_flags

echo "[build] Running assembleDebug (ABIs: $ABIS)…"
./gradlew assembleDebug -PreactNativeArchitectures="$ABIS" "${GRADLE_CONSTRAINT_FLAGS[@]}"

APK_SRC=$(find "$ANDROID_DIR/app/build/outputs/apk/debug" -name "*.apk" | head -1)
if [[ -z "$APK_SRC" ]]; then
  echo "[build] ERROR: No APK found after build" >&2
  exit 1
fi

# ── Verify the Sentry DSN reached the packaged bundle (PAP-1650) ─────────────
# `.env` lives at the REPO root, but the Expo project root is `mobile/`, so
# Expo CLI never auto-loads it. The DSN reaches the bundle only via the
# `set -a; source .env` step above. A bare `./gradlew assemble*` therefore
# produces an APK where sentry.js sees an empty DSN, never calls Sentry.init,
# and every telemetry path is dead — debug reports, training upload, chainring
# events and native crash handling. That is how b133 shipped dark. Assert
# against the artifact, not the environment, because only the artifact ships.
assert_sentry_dsn_bundled() {
  local apk="$1" tmp
  if [[ -z "${EXPO_PUBLIC_SENTRY_DSN:-}" ]]; then
    echo "[build] ERROR: EXPO_PUBLIC_SENTRY_DSN is unset — this build would ship with all" >&2
    echo "[build] telemetry disabled. Set it in $REPO_ROOT/.env (repo root, not mobile/)." >&2
    exit 1
  fi
  tmp=$(mktemp -d)
  if unzip -o -q "$apk" assets/index.android.bundle -d "$tmp" \
     && grep -q -a -F "$EXPO_PUBLIC_SENTRY_DSN" "$tmp/assets/index.android.bundle"; then
    rm -rf "$tmp"
    echo "[build] Verified Sentry DSN is baked into the packaged JS bundle"
  else
    rm -rf "$tmp"
    echo "[build] ERROR: EXPO_PUBLIC_SENTRY_DSN is set but is absent from the packaged" >&2
    echo "[build] bundle — the artifact would ship telemetry-dead. Refusing to publish." >&2
    exit 1
  fi
}
assert_sentry_dsn_bundled "$APK_SRC"

# ── Verify native Sentry is configured (PAP-1653) ─────────────────────────────
# The check above only proves JS can reach Sentry. The native SDK is started
# separately by `RNSentrySDK.init(this)` in MainApplication.onCreate, which
# reads its DSN from `assets/sentry.options.json`. Without that asset, JVM/NDK
# crashes and ANRs that happen before the JS bundle loads have no telemetry
# path. Both halves are produced by the @sentry/react-native Expo plugin at
# `expo prebuild` time, so a stale `android/` tree silently drops them.
# The DSN half asserts against the artifact, same as the bundle check; the
# RNSentrySDK.init half asserts against the android/ source tree the APK was
# just assembled from, because proving it from the artifact would mean
# dexdump'ing classes.dex.
#
# NOTE: `io.sentry.dsn` manifest meta-data is deliberately NOT used. The SDK
# ships `io.sentry.auto-init=false` in its own manifest, so sentry-android's
# SentryInitProvider ignores any DSN meta-data. The options-file path is the
# only one that actually starts the native SDK.
assert_sentry_native_configured() {
  local apk="$1" main_application tmp
  tmp=$(mktemp -d)
  if unzip -o -q "$apk" assets/sentry.options.json -d "$tmp" \
     && grep -q -a -F "$EXPO_PUBLIC_SENTRY_DSN" "$tmp/assets/sentry.options.json"; then
    rm -rf "$tmp"
    echo "[build] Verified Sentry DSN is baked into the packaged native options file"
  else
    rm -rf "$tmp"
    echo "[build] ERROR: assets/sentry.options.json is missing from the APK or does not" >&2
    echo "[build] carry the DSN — native crashes before JS init would go unreported." >&2
    echo "[build] Re-run 'npx expo prebuild -p android' from mobile/ with .env sourced." >&2
    exit 1
  fi

  # The options file is inert unless MainApplication actually starts the SDK.
  main_application=$(find "$ANDROID_DIR/app/src/main/java" -name 'MainApplication.kt' | head -1)
  if [[ -z "$main_application" ]] || ! grep -q 'RNSentrySDK.init' "$main_application"; then
    echo "[build] ERROR: MainApplication.kt does not call RNSentrySDK.init — the packaged" >&2
    echo "[build] sentry.options.json would never be read. Re-run 'npx expo prebuild'." >&2
    exit 1
  fi
  echo "[build] Verified MainApplication starts the native Sentry SDK"
}
assert_sentry_native_configured "$APK_SRC"

# ── Sentry source-map upload (PAP-1543) ───────────────────────────────────────
# Lets the Sentry stack trace UI map minified bundle frames back to source.
# Non-fatal if creds are missing or the upload fails — the APK still ships.
SENTRY_CLI="$MOBILE_DIR/node_modules/@sentry/cli/bin/sentry-cli"
if [[ -n "${SENTRY_AUTH_TOKEN:-}" && -n "${SENTRY_ORG:-}" && -n "${SENTRY_PROJECT:-}" && -x "$SENTRY_CLI" ]]; then
  echo "[build] Uploading source maps to Sentry (release=$BUILD_LABEL)…"
  (
    cd "$MOBILE_DIR"
    SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN" \
    SENTRY_ORG="$SENTRY_ORG" \
    SENTRY_PROJECT="$SENTRY_PROJECT" \
    "$SENTRY_CLI" sourcemaps upload \
      --release "$BUILD_LABEL" \
      --strip-prefix "$MOBILE_DIR" \
      "$ANDROID_DIR/app/build/generated/assets/createBundleDebugJsAndAssets" \
      "$ANDROID_DIR/app/build/intermediates/sourcemaps/react/debug" 2>&1
  ) || echo "[build] WARNING: Sentry sourcemap upload failed (non-fatal)." >&2
else
  echo "[build] Skipping Sentry sourcemap upload (SENTRY_AUTH_TOKEN / SENTRY_ORG / SENTRY_PROJECT or sentry-cli missing)."
fi

# ── Archive APK ───────────────────────────────────────────────────────────────
APK_NAME="gear-camera-debug-${BUILD_DATE}-b${BUILD_NUMBER}.apk"
APK_DEST="$TEST_BUILDS_DIR/$APK_NAME"
cp "$APK_SRC" "$APK_DEST"
APK_SIZE_MB=$(du -m "$APK_DEST" | cut -f1)

echo "[build] APK → $APK_DEST (${APK_SIZE_MB}MB)"

# ── Upload to GitHub Releases ────────────────────────────────────────────────
TAG="b${BUILD_NUMBER}"
# Sanitize APK name for upload — GitHub strips/replaces both spaces and colons
# in release asset filenames, so the README link must use the same dots.
UPLOAD_APK_NAME="${APK_NAME// /.}"
UPLOAD_APK_NAME="${UPLOAD_APK_NAME//:/.}"

UPLOAD_FAILED=0
if [[ -n "${SKIP_RELEASE_UPLOAD:-}" ]]; then
  DOWNLOAD_LINK="local only — SKIP_RELEASE_UPLOAD"
elif gh_publish_release "$TAG" "Debug Build b${BUILD_NUMBER}" \
       "Build b${BUILD_NUMBER} — v${VERSION} — ${BUILD_DATE}" \
       "$APK_DEST" "$UPLOAD_APK_NAME"; then
  DOWNLOAD_LINK="$GH_DOWNLOAD_LINK"
else
  DOWNLOAD_LINK="**UPLOAD FAILED — not delivered**"
  UPLOAD_FAILED=1
fi

# ── Update test-builds/README.md ──────────────────────────────────────────────
# Append a new row to the table.
TIMESTAMP_FULL=$(date +"%Y-%m-%d %H:%M")
NEW_ROW="| $TIMESTAMP_FULL | $APK_NAME (${APK_SIZE_MB}MB) | b${BUILD_NUMBER} | $DOWNLOAD_LINK |"

# Insert row after the table header line (the line starting with "| Date")
python3 - "$README" "$NEW_ROW" <<'PYEOF'
import sys, re
path, row = sys.argv[1], sys.argv[2]
with open(path) as f:
    content = f.read()
# Find the separator line (---|---) and insert after it
lines = content.splitlines(keepends=True)
result = []
inserted = False
for i, line in enumerate(lines):
    result.append(line)
    if not inserted and re.match(r'\|[-| ]+\|', line):
        result.append(row + '\n')
        inserted = True
if not inserted:
    result.append(row + '\n')
with open(path, 'w') as f:
    f.writelines(result)
print(f"[build] Updated {path}")
PYEOF

# The README row is written first so the build is still recorded, then the
# failed delivery is reported as the terminal state of the script (PAP-1655).
if (( UPLOAD_FAILED )); then
  gh_upload_failed_banner "$TAG" "$APK_DEST"
  exit 1
fi

echo "[build] Done. Build label: $BUILD_LABEL"
